language: python
matrix:
    include:
      # Python version is just for the look on travis.
        - python: 2.7
          env: TOX_ENV=py27-django18
        - python: 2.7
          env: TOX_ENV=py27-django19
        - python: 2.7
          env: TOX_ENV=py27-django110

        - python: 3.4
          env: TOX_ENV=py34-django18
        - python: 3.4
          env: TOX_ENV=py34-django19
        - python: 3.4
          env: TOX_ENV=py34-django110

        - python: 3.5
          env: TOX_ENV=py35-django18
        - python: 3.5
          env: TOX_ENV=py35-django19
        - python: 3.5
          env: TOX_ENV=py35-django110

        - env: TOX_ENV=flake8
script:
    - tox -e $TOX_ENV
install:
    - pip install tox
