language: python
python: 2.7
env:
  - TOX_ENV=py26-1.4
  - TOX_ENV=py26-1.5
  - TOX_ENV=py27-1.4
  - TOX_ENV=py27-1.5
  - TOX_ENV=py33-1.5
  - TOX_ENV=py33-1.6
  - TOX_ENV=py34-1.5
  - TOX_ENV=py34-1.6
  - TOX_ENV=flake8
script:
    - tox -e $TOX_ENV
install:
    - pip install tox
