name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:

    strategy:
      matrix:
        include:

          - name: Python 3.8 / Django 4.2
            python_version: "3.8"
            tox_env: py38-django42

          - name: Python 3.9 / Django 4.2
            python_version: "3.9"
            tox_env: py39-django42

          - name: Python 3.10 / Django 4.2
            python_version: "3.10"
            tox_env: py310-django42

          - name: Python 3.11 / Django 4.2
            python_version: "3.11"
            tox_env: py311-django42

          - name: Python 3.12 / Django 4.2
            python_version: "3.12"
            tox_env: py312-django42

          - name: Python 3.10 / Django 5.0
            python_version: "3.10"
            tox_env: py310-django50

          - name: Python 3.11 / Django 5.0
            python_version: "3.11"
            tox_env: py311-django50

          - name: Python 3.12 / Django 5.0
            python_version: "3.12"
            tox_env: py312-django50

          - name: Python 3.10 / Django 5.1
            python_version: "3.10"
            tox_env: py310-django51

          - name: Python 3.11 / Django 5.1
            python_version: "3.11"
            tox_env: py311-django51

          - name: Python 3.12 / Django 5.1
            python_version: "3.12"
            tox_env: py312-django51

          - name: Python 3.10 / Django 5.2
            python_version: "3.10"
            tox_env: py310-django52

          - name: Python 3.11 / Django 5.2
            python_version: "3.11"
            tox_env: py311-django52

          - name: Python 3.12 / Django 5.2
            python_version: "3.12"
            tox_env: py312-django52

          - name: Python 3.13 / Django 5.2
            python_version: "3.13"
            tox_env: py313-django52

          - name: Python 3.14 / Django 5.2
            python_version: "3.14"
            tox_env: py314-django52

          - name: Docs
            python_version: "3"
            tox_env: docs

          - name: Lint
            python_version: "3"
            tox_env: lint

    name: "${{ matrix.name }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Pip cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/
          key: ${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('setup.cfg') }}

      - name: Install Tox
        run: pip install tox

      - name: Run ${{ matrix.name }}
        run: tox
        env:
          TOXENV: "${{ matrix.tox_env }}"

  report-status:
    name: success
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Report success
        run: echo 'Success !'
